server:
  host: "0.0.0.0"
  port: 8765
  auth_token: "change-me-in-production"
  ssl: true

wyoming:
  host: "0.0.0.0"
  port: 10700  # Port to listen on (HA connects here)

audio:
  sample_rate: 16000
  channels: 1
  chunk_duration_ms: 30


client:
  overlay_url: "http://home-server.fritz.box:8123/view-assist/clock"

logging:
  level: "INFO"
  file: "hybrid-satellite.log"
